name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      # we don't cache because the docs say not to
      - run: npx playwright install --with-deps chromium
      - run: npm run build
      - run: npm run test

      - run: npm publish --access public
